name: Test CI

on:
    push:
        branches: ["main"]
    pull_request:
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: "0"

            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - uses: pnpm/action-setup@v4
              with:
                  run_install: true

            - run: pnpm run build
